apiVersion: 1

datasources:

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-telescope
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      username: __CLICKHOUSE_USER__
      defaultDatabase: telescope
      protocol: native
    secureJsonData:
      password: __CLICKHOUSE_PASSWORD__

  - name: Prometheus
    type: prometheus
    uid: prometheus-telescope
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 60s
